-- 通用图标
local icons = {
  LOADING = "􀖇",
  APPLE = "􀣺",
  PREFERENCES = "􀺽",
  ACTIVITY = "􀒓",
  LOCK = "􀒳",
  BELL = "􀋚",
  BELL_DOT = "􀝗",
  MUSIC = "􀑪",

  -- Git 图标
  GIT_ISSUE = "􀍷",
  GIT_DISCUSSION = "􀒤",
  GIT_PULL_REQUEST = "􀙡",
  GIT_COMMIT = "􀡚",
  GIT_INDICATOR = "􀂓",

  -- Spotify 图标
  SPOTIFY_BACK = "􀊎",
  SPOTIFY_PLAY_PAUSE = "􀊈",
  SPOTIFY_NEXT = "􀊐",
  SPOTIFY_SHUFFLE = "􀊝",
  SPOTIFY_REPEAT = "􀊞",

  -- Yabai 图标
  YABAI_STACK = "􀏭",
  YABAI_FULLSCREEN_ZOOM = "􀂓",
  YABAI_PARENT_ZOOM = "􀥃",
  YABAI_FLOAT = "􀢌",
  YABAI_GRID = "􀧍",
  YABAI_SPLIT_VERTICAL = "􀘜",
  YABAI_SPLIT_HORIZONTAL = "􀧋",

  -- 电池图标
  BATTERY_100 = "􀛨",
  BATTERY_75 = "􀺸",
  BATTERY_50 = "􀺶",
  BATTERY_25 = "􀛩",
  BATTERY_0 = "􀛪",
  BATTERY_CHARGING = "􀢋",

  -- 音量图标
  VOLUME_100 = "􀊩",
  VOLUME_66 = "􀊧",
  VOLUME_33 = "􀊥",
  VOLUME_10 = "􀊡",
  VOLUME_0 = "􀊣",

  ICON_CMD = "󰘳",
  ICON_COG = "����",
  ICON_CHART = "󱕍",
  ICON_LOCK = "󰌾",
  ICON_APP = "󰣆",

  ICON_PACKAGE = "󰏓",
  ICON_DEV = "󰅨",
  ICON_VSCODIUM = "",
  ICON_FILE = "󰉋",
  ICON_FINDER = "󰀶",
  ICON_GIT = "󰊢",
  ICON_LIST = "󱃔",
  ICON_SCREENSAVOR = "󱄄",
  ICON_WEATHER = "󰖕",
  ICON_MAIL = "󰇮",
  ICON_CALC = "󰪚",
  ICON_MAP = "󰆋",
  ICON_MICROPHONE = "󰍬",
  ICON_CHAT = "󰭻",
  ICON_VIDEOCHAT = "󰍫",
  ICON_NOTE = "󱞎",
  ICON_CAMERA = "󰄀",
  ICON_WEB = "󰇧",
  ICON_HOMEAUTOMATION = "󱉑",
  ICON_MUSIC = "􀫀",
  ICON_PODCAST = "󰦔",
  ICON_PLAY = "󱉺",
  ICON_BOOK = "󰂿",
  ICON_BOOKINFO = "󱁯",
  ICON_PREVIEW = "󰋲",
  ICON_PASSKEY = "󰷡",
  ICON_CAST = "󱒃",
  ICON_TABLE = "󰓫",
  ICON_PRESENT = "󰈩",
  ICON_CLOUD = "󰅧",
  ICON_PEN = "󰏬",
  ICON_REMOTEDESKTOP = "󰢹",
  ICON_CLOCK = "󰥔",
  ICON_CALENDAR = "󰃭",
  ICON_WIFI = "󰖩",
  ICON_WIFI_OFF = "󰖪",
  ICON_VPN = "󰦝",
  ICONS_VOLUME = {"󰸈", "󰕿", "󰖀", "󰕾"},
  ICONS_BATTERY = {"󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"},
  ICONS_BATTERY_CHARGING = {"󰢟", "󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂅"},
  ICON_SWAP = "󰁯",
  ICON_RAM = "󰓅",
  ICON_DISK = "󰋊",
  ICON_CPU = "󰘚",
  ICON_CONTROLCENTER = "􀜊",

  -- 我的应用
  ICON_DISCORD = "",
  ICON_TERM = "",
  ICON_PHOTOSHOP = "",
  ICON_AFTEREFFECTS = "󱁑",
  ICON_PHOTOS = "",
  ICON_FIGMA = "",
  ICON_KICAD = "",
  ICON_THINGS = "",
  ICON_DOWNLOAD = "􁾮",
  ICON_ICON = "􀼱",
  ICON_STEAM = "󰓓",
  ICON_HANDBRAKE = "󱁆",
  ICON_FIREFOX = "󰈹",
  ICON_FONTBOOK = "",
  ICON_GLM = "󰓃"
}

return icons
